### ISSUE TITLE
Ubuntu Virtual Machine Support

### ISSUE THREAD

**Issue by ErickDDM** [amzn/distance-assistant#5]
Hi! We are planning to deploy the app that you developed back in the office. Because of company policies we can only use Windows in our computers. As stated in the project README it is highly recommend to run the system in a Linux machine directly because exposing the camera to VM's is incredible tricky. Were you able to get the system running in a Ubuntu VM? What would you suggest? Thank you all for your amazing efforts!

**Comment by ericreg-amazon** [comment]
Hello and thank you for your inquiry. 

According to the documentation on the librealsense GitHub page “Due to the USB 3.0 translation layer between native hardware and virtual machine, the librealsense team does not support installation in a VM.” (https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md). Since librealsesne is not supported in a VM we did not try it. We are currently evaluating releasing Distance Assistant for other platform and OS combinations and will continue to post updates on GitHub once we know more.
